# Generated by Django 2.2.5 on 2019-09-23 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name=datetime.datetime(2019, 9, 23, 4, 29, 29, 373062, tzinfo=utc))),
            ],
        ),
    ]
