# Generated by Django 2.2.5 on 2019-09-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190923_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
