# Generated by Django 2.2.5 on 2019-09-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190923_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name_plural': 'notes'},
        ),
    ]
